const JSZip = require('jszip')

/**
 * Generate a downloadable ZIP buffer from an array of files.
 * @param {Array<{filename: string, content: string}>} files
 * @param {object} apiData - API metadata for README
 * @returns {Buffer} ZIP file buffer
 */
async function generateZip(files, apiData = {}) {
  const zip = new JSZip()

  // Add all generated files
  for (const file of files) {
    // Preserve directory structure if filename contains /
    zip.file(file.filename, file.content || '')
  }

  // Add project README if not already present
  const hasReadme = files.some(f => f.filename.toLowerCase() === 'readme.md')
  if (!hasReadme) {
    zip.file('README.md', generateProjectReadme(apiData, files))
  }

  // Add .env.example if it's a JS/Python project
  const hasEnv = files.some(f => f.filename.includes('.env'))
  if (!hasEnv && apiData.language !== 'java') {
    zip.file('.env.example', generateEnvExample(apiData))
  }

  // Add package.json for JS projects
  if (apiData.language === 'javascript') {
    const hasPkg = files.some(f => f.filename === 'package.json')
    if (!hasPkg) {
      zip.file('package.json', generatePackageJson(apiData))
    }
  }

  // Generate and return buffer
  const buffer = await zip.generateAsync({
    type: 'nodebuffer',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 },
  })

  return buffer
}

function generateProjectReadme(apiData, files) {
  const fileList = files.map(f => `- \`${f.filename}\``).join('\n')
  const langInstall = {
    javascript: '```bash\nnpm install\n```',
    python: '```bash\npip install httpx python-dotenv\n```',
    java: '```xml\n<!-- Add to pom.xml -->\n<dependency>\n  <groupId>com.squareup.okhttp3</groupId>\n  <artifactId>okhttp</artifactId>\n</dependency>\n```',
  }
  const langExt = { javascript: 'js', python: 'py', java: 'java' }
  const lang = apiData.language || 'javascript'

  return `# ${apiData.apiName || 'API'} Client

Generated by [Telo](https://telo.dev) — Transform API Documentation into Production-Ready Code.

## API Details

| Property | Value |
|----------|-------|
| API Name | ${apiData.apiName || 'N/A'} |
| Base URL | ${apiData.baseUrl || 'N/A'} |
| Version | ${apiData.version || 'N/A'} |
| Authentication | ${apiData.authType || 'N/A'} |
| Total Endpoints | ${apiData.totalEndpoints || 0} |
| Generated | ${new Date().toISOString().split('T')[0]} |

## Installation

${langInstall[lang] || ''}

## Setup

1. Copy \`.env.example\` to \`.env\`
2. Fill in your API credentials
3. Import and use the client

## Files in this package

${fileList}

## Quick Start

\`\`\`${langExt[lang]}
// See individual service files for complete examples
\`\`\`

## Documentation

Original API documentation: ${apiData.documentationUrl || 'See API provider'}

---

*Generated by Telo AI | ${new Date().toLocaleDateString()}*
`
}

function generateEnvExample(apiData) {
  const authLine = (apiData.authType || '').toLowerCase().includes('bearer')
    ? 'API_TOKEN=your_bearer_token_here'
    : (apiData.authType || '').toLowerCase().includes('api key')
    ? 'API_KEY=your_api_key_here'
    : 'API_TOKEN=your_token_here'

  return `# ${apiData.apiName || 'API'} Client Configuration
# Copy this file to .env and fill in your values

API_BASE_URL=${apiData.baseUrl || 'https://api.example.com'}
${authLine}
API_TIMEOUT=30000
API_MAX_RETRIES=3
`
}

function generatePackageJson(apiData) {
  const name = (apiData.apiName || 'api-client')
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9-]/g, '')

  return JSON.stringify({
    name: `${name}-client`,
    version: '1.0.0',
    description: `Auto-generated client for ${apiData.apiName || 'API'} — generated by Telo`,
    type: 'module',
    main: 'ApiClient.js',
    scripts: {
      test: 'echo "Add your tests here"',
    },
    dependencies: {
      axios: '^1.6.0',
      dotenv: '^16.0.0',
    },
    keywords: ['api-client', 'generated', 'telo'],
    license: 'MIT',
  }, null, 2)
}

module.exports = { generateZip }
